name: Build spider CLI

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build spider_cli
        run: |
          cargo install spider_cli \
            --version 2.52.4 \
            --root /tmp/spider
      - name: Strip binary
        run: strip /tmp/spider/bin/spider
      - uses: actions/upload-artifact@v4
        with:
          name: spider-linux-x86_64
          path: /tmp/spider/bin/spider